name: Cypress e2e integration tests workflow

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

env:
  OPENSEARCH_DASHBOARDS_VERSION: 'main'
  OPENSEARCH_VERSION: '3.0.0-beta1-SNAPSHOT'
  QUERY_INSIGHTS_BRANCH: 'main'
  GRADLE_VERSION: '7.6.1'

jobs:
  tests:
    name: Run Cypress E2E tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            cypress_cache_folder: ~/AppData/Local/Cypress/Cache
          - os: ubuntu-latest
            cypress_cache_folder: ~/.cache/Cypress
    runs-on: ${{ matrix.os }}
    env:
      CI: 1
      TERM: xterm

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Enable longer filenames
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true

      - name: Checkout Query Insights
        uses: actions/checkout@v4
        with:
          path: query-insights
          repository: opensearch-project/query-insights
          ref: ${{ env.QUERY_INSIGHTS_BRANCH }}

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Run OpenSearch with Query Insights plugin
        run: |
          cd query-insights
          ./gradlew run -Dopensearch.version=${{ env.OPENSEARCH_VERSION }} &
        shell: bash

      - name: Checkout OpenSearch-Dashboards
        uses: actions/checkout@v4
        with:
          repository: opensearch-project/OpenSearch-Dashboards
          path: OpenSearch-Dashboards
          ref: ${{ env.OPENSEARCH_DASHBOARDS_VERSION }}

      - name: Checkout Query Insights Dashboards plugin
        uses: actions/checkout@v4
        with:
          path: OpenSearch-Dashboards/plugins/query-insights-dashboards

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: './OpenSearch-Dashboards/.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn
        shell: bash
        run: |
          YARN_VERSION=$(node -p "require('./OpenSearch-Dashboards/package.json').engines.yarn")
          echo "Installing yarn@$YARN_VERSION"
          npm i -g yarn@$YARN_VERSION

      - run: node -v
      - run: yarn -v

      - name: Bootstrap plugin/OpenSearch-Dashboards
        run: |
          cd OpenSearch-Dashboards/plugins/query-insights-dashboards
          yarn osd bootstrap --single-version=loose

      - name: Run OpenSearch-Dashboards server
        run: |
          cd OpenSearch-Dashboards
          yarn start --no-base-path --no-watch --server.host="0.0.0.0" &
        shell: bash

      - name: Wait for OSD server (non-Windows)
        if: ${{ matrix.os != 'windows-latest' }}
        run: curl --retry 30 --retry-delay 10 --retry-connrefused --fail http://localhost:5601/api/status
        shell: bash

      - name: Wait for OSD server (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: Start-Sleep -s 600
        shell: powershell

      - name: Install Cypress
        run: |
          cd OpenSearch-Dashboards/plugins/query-insights-dashboards
          npx cypress install
        shell: bash

      - name: Get Cypress version
        id: cypress_version
        run: |
          echo "cypress_version=$(jq -r '.dependencies.cypress' OpenSearch-Dashboards/plugins/query-insights-dashboards/package.json)" >> $GITHUB_OUTPUT

      - name: Cache Cypress
        id: cache-cypress
        if: matrix.os == 'ubuntu-latest'
        uses: actions/cache@v4
        with:
          path: ${{ matrix.cypress_cache_folder }}
          key: cypress-cache-v4-${{ matrix.os }}-${{ github.run_id }}-${{ hashFiles('OpenSearch-Dashboards/plugins/query-insights-dashboards/package.json') }}

      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: OpenSearch-Dashboards/plugins/query-insights-dashboards
          command: yarn run cypress run
          wait-on: 'http://localhost:5601/'
          wait-on-timeout: 600
          browser: chrome
        env:
          CYPRESS_CACHE_FOLDER: ""

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.os }}
          path: OpenSearch-Dashboards/plugins/query-insights-dashboards/cypress/screenshots

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-${{ matrix.os }}
          path: OpenSearch-Dashboards/plugins/query-insights-dashboards/cypress/videos
